packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  msw: true
  simple-git-hooks: false
  vue-demi: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
