/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "activity_list-create": () => import("@/views/activity/list-create/index.vue"),
  "activity_list-question-detail": () => import("@/views/activity/list-question-detail/[id].vue"),
  "activity_list-question": () => import("@/views/activity/list-question/[id].vue"),
  activity_list: () => import("@/views/activity/list/index.vue"),
  "activity_question-create": () => import("@/views/activity/question-create/index.vue"),
  "activity_question-detail": () => import("@/views/activity/question-detail/[id].vue"),
  activity_question: () => import("@/views/activity/question/index.vue"),
  "content_about-diff": () => import("@/views/content/about-diff/index.vue"),
  "content_about-edit": () => import("@/views/content/about-edit/index.vue"),
  content_about: () => import("@/views/content/about/index.vue"),
  content_comment: () => import("@/views/content/comment/index.vue"),
  "content_feedback-detail": () => import("@/views/content/feedback-detail/[id].vue"),
  content_feedback: () => import("@/views/content/feedback/index.vue"),
  "content_help-create": () => import("@/views/content/help-create/index.vue"),
  "content_help-diff": () => import("@/views/content/help-diff/index.vue"),
  content_help: () => import("@/views/content/help/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "mall_product-create": () => import("@/views/mall/product-create/index.vue"),
  "mall_product-detail": () => import("@/views/mall/product-detail/[id].vue"),
  mall_product: () => import("@/views/mall/product/index.vue"),
  mall_redemption: () => import("@/views/mall/redemption/index.vue"),
  "mall_rules-diff": () => import("@/views/mall/rules-diff/index.vue"),
  mall_rules: () => import("@/views/mall/rules/index.vue"),
  "notice_list-create": () => import("@/views/notice/list-create/index.vue"),
  "notice_list-detail": () => import("@/views/notice/list-detail/[id].vue"),
  notice_list: () => import("@/views/notice/list/index.vue"),
  "review_answer-detail": () => import("@/views/review/answer-detail/[id].vue"),
  review_answer: () => import("@/views/review/answer/index.vue"),
  "review_question-detail": () => import("@/views/review/question-detail/[id].vue"),
  review_question: () => import("@/views/review/question/index.vue"),
  "user_list-detail": () => import("@/views/user/list-detail/[id].vue"),
  user_list: () => import("@/views/user/list/index.vue"),
};
