/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "login-callback": () => import("@/views/_builtin/login-callback/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  mall_exchange: () => import("@/views/mall/exchange/index.vue"),
  mall_goods: () => import("@/views/mall/goods/index.vue"),
  operation_activities: () => import("@/views/operation/activities/index.vue"),
  "operation_feedback-detail": () => import("@/views/operation/feedback-detail/[id].vue"),
  operation_feedback: () => import("@/views/operation/feedback/index.vue"),
  "operation_notice-form": () => import("@/views/operation/notice-form/[id].vue"),
  operation_notice: () => import("@/views/operation/notice/index.vue"),
  operation_other: () => import("@/views/operation/other/index.vue"),
  operation_questions: () => import("@/views/operation/questions/index.vue"),
  review_attempts: () => import("@/views/review/attempts/index.vue"),
  review_comments: () => import("@/views/review/comments/index.vue"),
  review_photos: () => import("@/views/review/photos/index.vue"),
  system_users: () => import("@/views/system/users/index.vue"),
};
