/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'login-callback',
    path: '/login/callback',
    component: 'layout.base$view.login-callback',
    meta: {
      title: 'login-callback',
      i18nKey: 'route.login-callback',
      hideInMenu: true,
      constant: true
    }
  },
  {
    name: 'mall',
    path: '/mall',
    component: 'layout.base',
    meta: {
      title: 'mall',
      i18nKey: 'route.mall',
      icon: 'mdi:storefront-outline',
      order: 4
    },
    children: [
      {
        name: 'mall_exchange',
        path: '/mall/exchange',
        component: 'view.mall_exchange',
        meta: {
          title: 'mall_exchange',
          i18nKey: 'route.mall_exchange',
          icon: 'mdi:ticket-confirmation-outline',
          order: 2
        }
      },
      {
        name: 'mall_goods',
        path: '/mall/goods',
        component: 'view.mall_goods',
        meta: {
          title: 'mall_goods',
          i18nKey: 'route.mall_goods',
          icon: 'mdi:package-variant-closed',
          order: 1
        }
      }
    ]
  },
  {
    name: 'operation',
    path: '/operation',
    component: 'layout.base',
    meta: {
      title: 'operation',
      i18nKey: 'route.operation',
      icon: 'mdi:calendar-month-outline',
      order: 3
    },
    children: [
      {
        name: 'operation_activities',
        path: '/operation/activities',
        component: 'view.operation_activities',
        meta: {
          title: 'operation_activities',
          i18nKey: 'route.operation_activities',
          icon: 'mdi:calendar-clock-outline',
          order: 1
        }
      },
      {
        name: 'operation_feedback',
        path: '/operation/feedback',
        component: 'view.operation_feedback',
        meta: {
          title: 'operation_feedback',
          i18nKey: 'route.operation_feedback',
          icon: 'mdi:message-alert-outline',
          order: 3
        }
      },
      {
        name: 'operation_feedback-detail',
        path: '/operation/feedback-detail/:id',
        component: 'view.operation_feedback-detail',
        meta: {
          title: 'operation_feedback-detail',
          i18nKey: 'route.operation_feedback-detail',
          icon: 'mdi:message-alert-outline',
          hideInMenu: true,
          activeMenu: 'operation_feedback'
        }
      },
      {
        name: 'operation_notice',
        path: '/operation/notice',
        component: 'view.operation_notice',
        meta: {
          title: 'operation_notice',
          i18nKey: 'route.operation_notice',
          icon: 'mdi:bell-outline',
          order: 2
        }
      },
      {
        name: 'operation_notice-form',
        path: '/operation/notice-form/:id',
        component: 'view.operation_notice-form',
        meta: {
          title: 'operation_notice-form',
          i18nKey: 'route.operation_notice-form',
          icon: 'mdi:bell-ring-outline',
          hideInMenu: true,
          activeMenu: 'operation_notice'
        }
      },
      {
        name: 'operation_other',
        path: '/operation/other',
        component: 'view.operation_other',
        meta: {
          title: 'operation_other',
          i18nKey: 'route.operation_other',
          icon: 'mdi:dots-horizontal-circle-outline',
          order: 4
        }
      },
      {
        name: 'operation_questions',
        path: '/operation/questions',
        component: 'view.operation_questions',
        meta: {
          title: 'operation_questions',
          i18nKey: 'route.operation_questions',
          icon: 'mdi:image-multiple-outline',
          order: 0
        }
      }
    ]
  },
  {
    name: 'review',
    path: '/review',
    component: 'layout.base',
    meta: {
      title: 'review',
      i18nKey: 'route.review',
      icon: 'mdi:clipboard-check-outline',
      order: 2
    },
    children: [
      {
        name: 'review_attempts',
        path: '/review/attempts',
        component: 'view.review_attempts',
        meta: {
          title: 'review_attempts',
          i18nKey: 'route.review_attempts',
          icon: 'mdi:map-check-outline',
          order: 2
        }
      },
      {
        name: 'review_comments',
        path: '/review/comments',
        component: 'view.review_comments',
        meta: {
          title: 'review_comments',
          i18nKey: 'route.review_comments',
          icon: 'mdi:comment-alert-outline',
          order: 3
        }
      },
      {
        name: 'review_photos',
        path: '/review/photos',
        component: 'view.review_photos',
        meta: {
          title: 'review_photos',
          i18nKey: 'route.review_photos',
          icon: 'mdi:image-check-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 5
    },
    children: [
      {
        name: 'system_users',
        path: '/system/users',
        component: 'view.system_users',
        meta: {
          title: 'system_users',
          i18nKey: 'route.system_users',
          icon: 'mdi:account-group-outline',
          order: 1
        }
      }
    ]
  }
];
